[workspace]
resolver = "2"
members = [
    "fx",
    "fx-api",
    "fx-runtime",
    "fx-runtime-common",
    "fx-server",
    "fx-dashboard",
    "fx-common",
    "fx-macro",
    "fx-services/fx-app-counter",
    "fx-services/fx-app-hello-world",
    "fx-services/fx-app-mocks",
    "fx-services/fx-app-rpc-test-service",
    "fx-services/fx-test-app"
]
