[package]
name = "fx-app-mocks"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
axum = { version = "0.8.4", default-features = false }

fx-sdk = { path = "../../fx-sdk" }
