[package]
name = "benchmark-baseline-axum"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
axum = "0.8.8"
tokio = { version = "1.49.0", features = ["full"] }
rusqlite = { version = "0.38.0", features = ["bundled"] }
yarte = "0.15.7"
