[package]
name = "fx-app-rpc-test-service"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
tracing = "0.1.41"
serde = { version = "1.0.219", features = ["derive"] }

fx-sdk = { path = "../../fx-sdk" }
